require: rubocop-rspec

RSpec/MultipleExpectations:
  Max: 4
RSpec/InstanceVariable:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - Gemfile
    - proc-wait3.gemspec
    - Rakefile
    - examples/*.rb

Naming/FileName:
  Enabled: false
Style/GlobalVars:
  Enabled: false
